name: Build and Deploy to Azure Storage Static Website

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_STORAGE_ACCOUNT: angursweb01         # Your storage account name
  AZURE_STORAGE_CONTAINER: '$web'            # Static website container is always $web

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the app
        run: npm run build

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    # JSON creds for a Service Principal with Storage Blob Contributor role

      - name: Upload dist folder to Azure Storage $web container
        run: |
          az storage blob upload-batch \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --destination ${{ env.AZURE_STORAGE_CONTAINER }} \
            --source ./dist \
            --overwrite
